"use client";
import { useState } from "react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Input } from "../components/ui/input";
import { Textarea } from "../components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { Check, Camera, Film, Rocket, Timer, Sparkles, Star, Mail, Phone } from "lucide-react";
const LOGO_LIGHT = "/logo-ke-black.png";
const LOGO_DARK = "/logo-ke-white.png";
const features = [
  { icon: Timer, title: "3 ngày giao hàng", desc: "Pipeline rút gọn – một vòng feedback, gỡ watermark sau thanh toán." },
  { icon: Rocket, title: "Tốc độ thanh khoản", desc: "Hợp đồng & đặt cọc online, link thanh toán nhanh, gửi file qua CDN." },
  { icon: Sparkles, title: "Preset & Template", desc: "Giảm 40% thời gian hậu kỳ." },
];
const packages = [{name:"Quick Media – 3 Day Sprint",price:"2.990.000₫",highlight:true,points:["01 video 15–45s","1 vòng feedback","Xuất 9:16 + 1:1","Caption template"],cta:"Đặt lịch nhanh"},
{name:"Product Photo – KV",price:"1.690.000₫",points:["05 ảnh KV","Retouch tiêu chuẩn","1 concept"],cta:"Nhận báo giá"},
{name:"Performance Ad Video",price:"3.490.000₫",points:["01 video bán hàng 20–30s","Motion headline","A/B opening"],cta:"Đặt làm ngay"},
{name:"Combo Video + Photo",price:"4.990.000₫",points:["01 video + 05 ảnh","Ưu tiên lịch quay 24h","Tặng 03 thumbnail"],cta:"Chốt lịch"}];
const concepts = ["UGC kể chuyện","Studio Minimal","Lifestyle Natural","Performance Ads","Luxury Detail","Educational/Insight"];
const portfolio = [
  {title:"Nước hoa – Luxury Detail", tag:"Luxury", thumb:"https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop"},
  {title:"Skincare – UGC Review", tag:"UGC", thumb:"https://images.unsplash.com/photo-1612815154858-60aa4c59eaa0?q=80&w=1200&auto=format&fit=crop"},
  {title:"Đồ uống – Lifestyle", tag:"Lifestyle", thumb:"https://images.unsplash.com/photo-1517705008128-361805f42e86?q=80&w=1200&auto=format&fit=crop"}
];
function Section({ id, children, className="" }: any){ return <section id={id} className={`container mx-auto px-4 md:px-6 ${className}`}>{children}</section>}
function Feature({ Icon, title, desc }: any){ const I = Icon; return (<Card className="shadow-sm"><CardHeader className="space-y-2"><div className="w-10 h-10 rounded-2xl bg-gray-100 flex items-center justify-center"><I className="w-5 h-5"/></div><CardTitle className="text-base">{title}</CardTitle><CardDescription>{desc}</CardDescription></CardHeader></Card>);}
function PackageCard({ p }: any){ return (<Card className={`relative shadow-sm ${p.highlight ? "border border-black/20" : ""}`}><CardHeader><CardTitle>{p.name}</CardTitle><CardDescription>Áp dụng cho 1 sản phẩm/1 lần sản xuất</CardDescription></CardHeader><CardContent className="space-y-3"><div className="text-3xl font-semibold">{p.price}</div><ul className="space-y-2">{p.points.map((pt:string,i:number)=>(<li key={i} className="flex items-start gap-2"><Check className="w-4 h-4 mt-1"/><span>{pt}</span></li>))}</ul></CardContent><CardFooter><Button className="w-full">{p.cta}</Button></CardFooter></Card>);}
function ContactCard(){ return (<Card className="shadow-sm"><CardHeader><CardTitle>Liên hệ nhanh</CardTitle><CardDescription>Nhận báo giá trong 15 phút làm việc</CardDescription></CardHeader><CardContent className="grid gap-3"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><a href="mailto:hello@kemedia.vn" className="inline-flex items-center gap-2 rounded-xl border p-3 hover:bg-gray-50"><Mail className="w-4 h-4"/><span>Email</span></a><a href="tel:+84900000000" className="inline-flex items-center gap-2 rounded-xl border p-3 hover:bg-gray-50"><Phone className="w-4 h-4"/><span>Hotline</span></a></div><div className="flex items-center gap-2 text-sm text-gray-500"><Star className="w-4 h-4"/><span>Ưu tiên lịch quay trong 24h với gói Combo</span></div></CardContent></Card>);}
export default function KEMediaPortfolio(){
  const [activeTag, setActiveTag] = useState("All");
  const tags = ["All", ...Array.from(new Set(portfolio.map(p=>p.tag)))];
  return (<div className="min-h-screen bg-white text-black">
    <header className="sticky top-0 z-40 border-b bg-white/80 backdrop-blur"><div className="container mx-auto px-4 md:px-6 h-14 flex items-center justify-between"><a href="#home" className="flex items-center gap-2" aria-label="KẾ Media"><img src={LOGO_LIGHT} alt="KẾ Media" className="h-7 w-auto"/></a><nav className="hidden md:flex items-center gap-6 text-sm"><a href="#services" className="hover:opacity-80">Dịch vụ</a><a href="#portfolio" className="hover:opacity-80">Portfolio</a><a href="#process" className="hover:opacity-80">Quy trình 3 ngày</a><a href="#contact" className="hover:opacity-80">Liên hệ</a></nav><Button asChild size="sm"><a href="#contact">Nhận báo giá</a></Button></div></header>
    <Section id="home" className="py-14 md:py-24"><div className="grid md:grid-cols-2 gap-8 items-center">
      <div className="space-y-6"><h1 className="text-3xl md:text-5xl font-bold leading-tight">Sản xuất media <span className="text-blue-600">Nhanh – Gọn – Bán được hàng</span></h1>
      <p className="text-gray-500 text-base md:text-lg">Gói <strong>Quick Media – 3 Day Sprint</strong>: nhận brief, quay/chụp, hậu kỳ và giao file trong 72 giờ.</p>
      <div className="flex flex-wrap gap-2">{concepts.map(c=>(<Badge key={c}>{c}</Badge>))}</div>
      <div className="flex gap-3"><Button asChild size="lg"><a href="#services"><Film className="w-4 h-4 mr-2"/>Xem gói dịch vụ</a></Button><Button variant="outline" asChild size="lg"><a href="#portfolio"><Camera className="w-4 h-4 mr-2"/>Xem portfolio</a></Button></div></div>
      <div className="aspect-[4/3] rounded-3xl overflow-hidden shadow-xl bg-gray-100 flex items-center justify-center"><img src={LOGO_LIGHT} alt="KẾ Media" className="h-20 w-auto opacity-80"/></div>
    </div></Section>
    <Section className="py-10"><div className="grid md:grid-cols-3 gap-4">{features.map((f,i)=>(<Feature key={i} Icon={f.icon} title={f.title} desc={f.desc}/>))}</div></Section>
    <Section id="services" className="py-16"><div className="max-w-2xl mb-8"><h2 className="text-2xl md:text-4xl font-bold">Gói dịch vụ</h2><p className="text-gray-500 mt-2">Chọn nhanh – báo giá rõ ràng – không phát sinh ngoài phạm vi.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{packages.map((p,idx)=>(<PackageCard key={idx} p={p}/>))}</div><p className="text-xs text-gray-500 mt-4">* Giá tham khảo cho 1 sản phẩm.</p></Section>
    <Section id="portfolio" className="py-16"><div className="flex items-end justify-between gap-4 mb-6"><div><h2 className="text-2xl md:text-4xl font-bold">Portfolio chọn lọc</h2><p className="text-gray-500 mt-2">Một số dự án tiêu biểu gần đây.</p></div><div className="hidden md:flex gap-2">{tags.map(t=>(<Button key={t} variant={activeTag===t?"default":"outline"} size="sm" onClick={()=>setActiveTag(t)}>{t}</Button>))}</div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{portfolio.filter(p=>activeTag==="All"||p.tag===activeTag).map((item,i)=>(<div key={i} className="group relative overflow-hidden rounded-2xl border bg-gray-100"><img src={item.thumb} alt={item.title} className="h-56 w-full object-cover transition-transform group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"/><div className="absolute bottom-3 left-3 text-white"><div className="text-sm opacity-80">{item.tag}</div><div className="font-medium">{item.title}</div></div></div>))}</div><div className="mt-4 flex md:hidden gap-2 overflow-x-auto">{tags.map(t=>(<Button key={t} variant={activeTag===t?"default":"outline"} size="sm" onClick={()=>setActiveTag(t)}>{t}</Button>))}</div></Section>
    <Section id="process" className="py-16"><div className="max-w-2xl mb-8"><h2 className="text-2xl md:text-4xl font-bold">Quy trình 3 ngày</h2><p className="text-gray-500 mt-2">Chuẩn hoá để tăng tốc – giảm vòng lặp – đảm bảo chất lượng.</p></div><div className="grid md:grid-cols-3 gap-4"><Card><CardHeader><CardTitle>Ngày 1 – Brief & Concept</CardTitle><CardDescription>Chốt concept, shotlist; đặt cọc 50–70%.</CardDescription></CardHeader><CardContent className="text-sm text-gray-500">Tạo task, gắn preset phù hợp concept. Sắp lịch quay/chụp.</CardContent></Card><Card><CardHeader><CardTitle>Ngày 2 – Quay/Chụp</CardTitle><CardDescription>Chọn raw, dựng nháp layout.</CardDescription></CardHeader><CardContent className="text-sm text-gray-500">Gửi preview ngắn; nhận feedback trong 2–3 giờ.</CardContent></Card><Card><CardHeader><CardTitle>Ngày 3 – Hậu kỳ & Giao</CardTitle><CardDescription>Xuất file; gửi link tải + hoá đơn.</CardDescription></CardHeader><CardContent className="text-sm text-gray-500">Thanh toán phần còn lại để gỡ watermark.</CardContent></Card></div></Section>
    <Section id="contact" className="py-16"><div className="grid md:grid-cols-2 gap-6 items-start"><div className="space-y-4"><h2 className="text-2xl md:text-4xl font-bold">Bắt đầu ngay hôm nay</h2><p className="text-gray-500">Gửi 3 đề xuất concept phù hợp trong 12 giờ làm việc.</p><ContactCard/></div><Card className="shadow-sm"><CardHeader><CardTitle>Yêu cầu báo giá</CardTitle><CardDescription>Điền nhanh để team phản hồi ngay.</CardDescription></CardHeader><CardContent className="grid gap-3"><Input placeholder="Tên doanh nghiệp / cá nhân"/><Input type="email" placeholder="Email"/><Input type="tel" placeholder="Số điện thoại"/><Tabs defaultValue="video" className="w-full"><TabsList className="grid grid-cols-3"><TabsTrigger value="video">Video</TabsTrigger><TabsTrigger value="photo">Ảnh</TabsTrigger><TabsTrigger value="combo">Combo</TabsTrigger></TabsList><TabsContent value="video" className="pt-3 text-sm text-gray-500">01 video 15–45s, tối ưu Ads.</TabsContent><TabsContent value="photo" className="pt-3 text-sm text-gray-500">05 ảnh key visual.</TabsContent><TabsContent value="combo" className="pt-3 text-sm text-gray-500">01 video + 05 ảnh.</TabsContent></Tabs><Textarea placeholder="Mô tả nhanh về sản phẩm / mục tiêu"/></CardContent><CardFooter><Button className="w-full">Gửi yêu cầu</Button></CardFooter></Card></div></Section>
    <footer className="border-t py-8"><Section className="flex flex-col md:flex-row items-center justify-between gap-3"><p className="text-sm text-gray-500">© {new Date().getFullYear()} KẾ Media. All rights reserved.</p><div className="flex gap-3 text-sm"><a className="hover:opacity-80" href="#services">Dịch vụ</a><a className="hover:opacity-80" href="#portfolio">Portfolio</a><a className="hover:opacity-80" href="#contact">Liên hệ</a></div></Section></footer>
  </div>);
}